@startuml Card
  class "Card" as Card {
    #value : 
    +set(value)
    +getValue()
    +getAsString()
  }
  class "CardGraphic" as CardGraphic {
    -colors : array
    -values : array
    -representation : array
    -buildArrayOfCards()
    +getAsString()
  }
  class "DeckOfCards" as DeckOfCards {
    -deck : 
    -buildDeck()
    +shuffle()
    +drawCard()
    +getNumberOfCards()
    +getDeckAsValues()
    +getDeck()
  }
  class "CardHand" as CardHand {
    -hand : 
    +add(card)
    +getNumberCards()
    +getValues()
    +getString()
  }
  Card <|-- CardGraphic
  CardHand *.. CardGraphic
  DeckOfCards *.. CardGraphic
@enduml