# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # To make markdown work..
    League\CommonMark\GithubFlavoredMarkdownConverter:
        tags: [ 'twig.markdown.converter' ]
    League\CommonMark\Extension\Table\TableExtension:
        tags: [ 'twig.markdown.league_extension' ]
    League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension:
        tags: [ 'twig.markdown.league_extension' ]
#    League\CommonMark\Extension\TableOfContents\TableOfContentsExtension:
#        tags: [ 'twig.markdown.league_extension' ]


